Repository Smarteon/loxone-java, pull requests merged in 2019-12, with the labels that each got.

#52 Allow token auto refresh
  src/main/java/cz/smarteon/loxone/Command.java
  src/main/java/cz/smarteon/loxone/LoxoneAuth.java
  src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
  src/main/java/cz/smarteon/loxone/TokenState.java
  src/main/java/cz/smarteon/loxone/message/EncryptedCommand.java
  src/test/groovy/cz/smarteon/loxone/CommandTest.groovy
  src/test/groovy/cz/smarteon/loxone/CryptoSupport.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneAuthTest.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
  src/test/groovy/cz/smarteon/loxone/MockWebSocketServer.groovy
  src/test/groovy/cz/smarteon/loxone/TokenStateTest.groovy
Labels: enhancement

#53 Few trivial changes
  src/main/java/cz/smarteon/loxone/CommandResponseListener.java
  src/main/java/cz/smarteon/loxone/LoxoneAuth.java
  src/main/java/cz/smarteon/loxone/message/ControlCommand.java
Labels: enhancement

#57 Fix ApiInfo problem in version 10.3.11.27
  src/main/java/cz/smarteon/loxone/message/ApiInfo.java
  src/test/groovy/cz/smarteon/loxone/message/ApiInfoTest.groovy
  src/test/resources/message/apiInfo103.json
Labels: Loxone 10.3

#58 Introduce web socket auto restart
  src/main/java/cz/smarteon/loxone/LoxoneAuth.java
  src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
  src/main/java/cz/smarteon/loxone/LoxoneWebsocketClient.java
  src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketIT.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
Labels: enhancement

#59 Introduce 1-wire details
  src/main/java/cz/smarteon/loxone/message/LoxoneMessageCommand.java
  src/main/java/cz/smarteon/loxone/message/OneWireDetails.java
  src/test/groovy/cz/smarteon/loxone/message/OneWireDetailsTest.groovy
  src/test/resources/message/oneWireDetails.json
Labels: enhancement

#60 Fix Hashing problem in version 10.3.11.27
  src/main/java/cz/smarteon/loxone/message/Hashing.java
  src/test/groovy/cz/smarteon/loxone/CryptoSupport.groovy
  src/test/groovy/cz/smarteon/loxone/message/HashingTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/LoxoneMessageTest.groovy
  src/test/resources/message/getKeyMessage.json
  src/test/resources/message/hashing_10_2.json
  src/test/resources/message/hashing_10_3.json
Labels: bug

#54 Loxone class as library main entrypoint
  src/main/java/cz/smarteon/loxone/Loxone.java
  src/main/java/cz/smarteon/loxone/LoxoneAppListener.java
  src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java
  src/main/java/cz/smarteon/loxone/LoxoneWebSocketListener.java
  src/test/groovy/cz/smarteon/loxone/LoxoneAT.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneTest.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketAT.groovy
  src/test/groovy/cz/smarteon/loxone/LoxoneWebSocketTest.groovy
Labels: enhancement

#62 Fix missing types in value type resolver
  src/main/java/cz/smarteon/loxone/message/LoxoneMessageCommand.java
  src/main/java/cz/smarteon/loxone/message/LoxoneValueTypeResolver.java
  src/test/groovy/cz/smarteon/loxone/message/LoxoneValueTypeResolverTest.groovy
Labels: bug

#63 Some trivials
  src/main/java/cz/smarteon/loxone/app/LoxoneApp.java
  src/main/java/cz/smarteon/loxone/message/LoxoneMessage.java
  src/test/groovy/cz/smarteon/loxone/app/LoxoneAppTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/LoxoneMessageTest.groovy
Labels: enhancement

#66 Allow to use APP token type
  src/main/java/cz/smarteon/loxone/LoxoneAuth.java
  src/main/java/cz/smarteon/loxone/message/EncryptedCommand.java
  src/main/java/cz/smarteon/loxone/message/TokenPermissionType.java
  src/test/groovy/cz/smarteon/loxone/LoxoneAuthTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/EncryptedCommandTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/TokenPermissionTypeTest.groovy
Labels: enhancement

#67 Convenient cast of JsonValue to other values
  src/main/java/cz/smarteon/loxone/Codec.java
  src/main/java/cz/smarteon/loxone/message/JsonValue.java
  src/test/groovy/cz/smarteon/loxone/CodecTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/JsonValueTest.groovy
Labels: enhancement

#69 Some minor fixes
  src/main/java/cz/smarteon/loxone/Loxone.java
  src/test/groovy/cz/smarteon/loxone/app/ControlTest.groovy
  src/test/groovy/cz/smarteon/loxone/app/LoxoneAppTest.groovy
  src/test/groovy/cz/smarteon/loxone/app/MiniserverInfoTest.groovy
  src/test/groovy/cz/smarteon/loxone/app/MiniserverUserTest.groovy
  src/test/resources/app/LoxAPP3.json
  src/test/resources/app/alarmControl.json
  src/test/resources/app/miniserverInfo.json
  src/test/resources/app/miniserverUser.json
  src/test/resources/app/switchControl.json
Labels: bug

#70 Loxone events javadoc, tests and nullability
  src/main/java/cz/smarteon/loxone/LoxoneEventListener.java
  src/main/java/cz/smarteon/loxone/message/LoxoneEvent.java
  src/main/java/cz/smarteon/loxone/message/TextEvent.java
  src/main/java/cz/smarteon/loxone/message/ValueEvent.java
  src/test/groovy/cz/smarteon/loxone/message/LoxoneEventTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/TextEventTest.groovy
  src/test/groovy/cz/smarteon/loxone/message/ValueEventTest.groovy
Labels: enhancement
